### ISSUE TITLE
Activity Execution and Compensation Retry

### ISSUE THREAD

**Issue by phatboyg** [MassTransit/MassTransit-Courier#7]
When an activity throws an exception, it faults the routing slip and does not retry the activity. This is in contrast to a regular consumer, which will retry `n` times before moving the message to the error queue. Allow an activity to opt-in to the ability to retry up to a specified number of times by resending the routing slip to the same activity with a retry count specified. Compensation should also support this level of retry capability.

**Comment by nipunjoshi** [comment]
Has this been implemented yet? Also, I noticed that when an exception is thrown from an Activity, the message gets simply purged and no error queue is created.. ? Is this how it behaves or am I missing something?

Thanks!

**Comment by phatboyg** [comment]
Activity execution in MT3 will support the same middleware configuration as a consumer, so runtime retry and other exception handling policies can be applied to the activities. 

In the case of routing slips, it's not a default behavior to create an error queue, because the composition of the itinerary for the routing slip may need to be rebuilt based on the state of the routing slip itself. That being said, with the middleware support in MT3, it would be feasible to apply a component to store the routing slip in an error queue upon failure.

The notification that the RoutingSlipFaulted should signal the initiating component such that it could recreate the routing slip as needed. I plan to prepare a complete example of how this works in the near future as the release of MT3 approaches.

**Comment by nipunjoshi** [comment]
Ok, makes sense. But we do not have a middleware orchestration service that could alter the itinerary. So, can it be something simple like in case of an exception, the Activity simply publishes the message to an error queue?

Something like this...

 public ExecutionResult Execute(Execution<TArguments> execution)
        {
            try
            {
                //Process() and call ExecutionResult Completed()
                //if throws exception
            }
            catch (Exception ex)
            {
                //Publish to the same Activity and retry n times
                //if still fails then Publish to error queue
            }
}

**Comment by phatboyg** [comment]
This will be working properly in 3.5.1
